#!/usr/bin/env bash
# This script displays `To infinity and beyond` indefinitely

cleanup() {
    echo "I am invincible!!!"
}

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap cleanup SIGTERM
done
